ARDUINO_DIR  = /usr/share/arduino
USER_LIB_PATH = /home/pi/sketchbook/libraries
ARDUINO_LIBS = DallasTemperature OneWire
MONITOR_BAUDRATE  = 9600




# Arduino Uno - standard for Entomatic - baudrate is default 19200
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE = 115200

# For the Entomatic Prototype - Nano with "old bootloader" 
BOARD_TAG    = nano328
#BOARD_SUB     = atmega328
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE = 57600

include /usr/share/arduino/Arduino.mk
